// Generated by evaluate:guardrails; see docs/guardrail-evaluation.json.
export const calibration = {
  provider: 'google',
  model: 'gemini-embedding-001',
  dimensions: 1536,
  version: 'content-v1',
  threshold: 0.594082320089203,
} as const;
